# ベースイメージ：Microsoft製の開発用Pythonコンテナ
FROM mcr.microsoft.com/devcontainers/python:3.12

# 必要であれば追加のOSパッケージを入れる
# RUN apt-get update && apt-get install -y build-essential

# ワークディレクトリ
WORKDIR /workspaces/aiagent_portfolio
